// Plain stylesheet imports such as `import "@/styles/globals.css"` are
// side-effect only. TypeScript 6 checks that side-effect imports resolve
// (noUncheckedSideEffectImports), and next-env.d.ts, which declares these, is
// generated by Next and not committed, so typecheck needs its own declaration.
declare module "*.css" {}
